"use client";

import { useRef } from "react";
import { motion, useScroll, useTransform } from "framer-motion";

function Section({ title, children, align = "left" }: { title: string, children: React.ReactNode, align?: "left" | "right" }) {
    return (
        <motion.div 
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.8 }}
            className={`min-h-[80vh] flex flex-col justify-center ${align === "right" ? "items-end text-right" : "items-start text-left"}`}
        >
            <h2 className="text-4xl md:text-6xl font-bold mb-8 text-white/90 tracking-tighter">
                {title}
            </h2>
            <div className={`max-w-xl text-lg md:text-xl text-white/70 leading-relaxed ${align === "right" ? "ml-auto" : "mr-auto"}`}>
                {children}
            </div>
        </motion.div>
    );
}

export default function Technology() {
  return (
    <div className="bg-black/40 text-white pt-24 px-6 md:px-24 pb-24 relative">
       
       {/* Background Grid Line for Context */}
       <div className="absolute left-6 md:left-24 top-0 bottom-0 w-[1px] bg-gradient-to-b from-transparent via-blue-500/30 to-transparent" />

       <div className="max-w-6xl mx-auto pl-8 md:pl-16">
            
            {/* Intro */}
            <div className="min-h-[60vh] flex flex-col justify-center">
                <span className="text-blue-400 font-mono text-sm tracking-widest mb-4">ARC TECHNOLOGY STACK v4.0</span>
                <h1 className="text-6xl md:text-8xl font-bold mb-8 tracking-tighter">
                    Zero Point <br/>
                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
                        Energy Field
                    </span>
                </h1>
                <p className="text-2xl text-white/60 max-w-2xl leading-relaxed">
                    A self-sustaining ionization loop that creates clean, infinite energy through controlled cold fusion.
                </p>
                <div className="mt-12 animate-bounce text-white/30">
                    Scroll to explore system architecture ↓
                </div>
            </div>

            {/* Data Stream Divider */}
            <div className="overflow-hidden whitespace-nowrap opacity-20 my-10 font-mono text-[10px] text-blue-500 select-none">
                {[...Array(5)].map((_, i) => (
                    <div key={i} className="animate-marquee inline-block">
                        010101001 0xFF 0x4A CORE_CYCLES_WAVEFORM_ANALYSIS 8839210.44391 TARGET_LOCK 0.00032 ERROR_NULL // 
                    </div>
                ))}
            </div>

            {/* Sections */}
            <Section title="Magnetic Confinement">
                <p className="mb-6">
                    The plasma stream is held in place by a rotating torus of high-intensity magnetic fields generated by a Halbach array of rare-earth magnets.
                </p>
                <div className="p-6 border border-blue-500/30 bg-blue-500/5 rounded-xl backdrop-blur-sm">
                    <h4 className="text-blue-400 font-bold mb-2 text-sm uppercase tracking-widest">Technical Insight</h4>
                    <p className="text-sm">
                        This containment prevents the super-heated core (5,400 K) from touching the chassis sidewalls, allowing the device to remain cool to the touch.
                    </p>
                </div>
            </Section>

            <Section title="Palladium Core" align="right">
                <p className="mb-6">
                    At the center lies a hockey-puck sized ring of Palladium-106. This isotope acts as the primary catalyst, breaking down hydrogen atoms at room temperature.
                </p>
                <ul className="text-sm space-y-2 text-white/50 inline-block text-left">
                    <li className="flex items-center gap-2"><div className="w-2 h-2 bg-purple-500 rounded-full"/> Catalyst Decay Rate: Negligible</li>
                    <li className="flex items-center gap-2"><div className="w-2 h-2 bg-purple-500 rounded-full"/> Isotope Purity: 99.999%</li>
                    <li className="flex items-center gap-2"><div className="w-2 h-2 bg-purple-500 rounded-full"/> Replacement Cycle: 10 Years</li>
                </ul>
            </Section>

            <Section title="Active Cooling">
                <p className="mb-6">
                    While the plasma field is magnetically isolated, radiant heat is managed by a closed-loop liquid nitrogen cooling system pumped through micro-channels in the chassis.
                </p>
                <div className="grid grid-cols-2 gap-4">
                     <div className="bg-white/5 p-4 rounded text-center">
                         <span className="block text-2xl font-bold text-white">77 K</span>
                         <span className="text-[10px] text-white/40 uppercase">Coolant Temp</span>
                     </div>
                     <div className="bg-white/5 p-4 rounded text-center">
                         <span className="block text-2xl font-bold text-white">40 PSI</span>
                         <span className="text-[10px] text-white/40 uppercase">Pump Pressure</span>
                     </div>
                </div>
            </Section>

            <Section title="Energy Conversion" align="right">
                <p>
                    Energy is extracted directly from the ionization layer using palladium collectors, bypassing the need for inefficient steam turbines or heat exchangers found in traditional fission reactors.
                </p>
                <p className="mt-4 text-green-400 font-mono">
                    &gt; EFFICIENCY RATING: 99.9%
                </p>
            </Section>
            
            {/* System Architecture Grid */}
            <div className="mt-32 mb-12">
                <h3 className="text-2xl font-bold mb-8 border-l-4 border-blue-500 pl-4">System Architecture & Telemetry</h3>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                    {[
                        { label: "Plasma Injector", val: "NOMINAL", color: "green" },
                        { label: "Magnetic Torus", val: "40,000 RPM", color: "blue" },
                        { label: "Coolant Flow", val: "450 L/min", color: "cyan" },
                        { label: "Core Temp", val: "5,400 K", color: "orange" },
                        { label: "Output Voltage", val: "120 kV", color: "purple" },
                        { label: "Harmonic Res.", val: "0.03%", color: "green" },
                        { label: "Containment", val: "100%", color: "blue" },
                        { label: "Fuel Cell", val: "98.2%", color: "green" },
                        { label: "Backup Battery", val: "READY", color: "green" },
                        { label: "Net Latency", val: "12 ms", color: "white" },
                        { label: "Key Rotation", val: "60s", color: "white" },
                        { label: "Seismic Stabil.", val: "ACTIVE", color: "blue" },
                        { label: "Ext. Radiation", val: "0.00 mSv", color: "green" },
                        { label: "System Uptime", val: "400 Days", color: "purple" },
                        { label: "Efficiency", val: "99.99%", color: "cyan" }
                    ].map((item, i) => (
                        <div key={i} className="bg-white/5 border border-white/5 p-4 rounded-xl hover:bg-white/10 hover:scale-105 transition-all group">
                            <div className="text-[10px] text-white/40 uppercase tracking-widest mb-1">{item.label}</div>
                            <div className={`text-sm font-bold font-mono text-${item.color}-400 group-hover:text-white transition-colors`}>
                                {item.val}
                            </div>
                            <div className="w-full h-0.5 bg-white/10 mt-2 rounded-full overflow-hidden">
                                <div className={`h-full bg-${item.color}-500/50 w-2/3 group-hover:w-full transition-all duration-500`} />
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Footer Area */}
            <div className="h-[40vh] flex items-center justify-center border-t border-white/10 mt-24">
                <div className="text-center">
                    <h3 className="text-3xl font-bold mb-4">Ready to upgrade?</h3>
                    <a href="/login" className="inline-block px-8 py-3 bg-white text-black font-bold rounded-full hover:bg-blue-400 transition-colors">
                        View Installation Guide
                    </a>
                </div>
            </div>

       </div>
    </div>
  );
}
